<h3><?= $this->view->loginerror; ?></h3>
<br>
<form action="../../../authserver/api.php?action=login&callback=<?= BASE ?>" method="post">
    <table>
        <tr>
            <td><label for="username">Gebruikersnaam</label></td>
            <td><input type="text" name="username" id="username"></td>
        </tr>
        <tr>
            <td><label for="password">Wachtwoord</label></td>
            <td><input type="password" name="password" id="password"></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Inloggen"></td>
        </tr>
    </table>
</form>