<!DOCTYPE html>
<html>
<head lang="nl">
    <meta charset="UTF-8">
    <meta name="robots" content="noindex">

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="<?= BASE; ?>/css/default.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <?php
        if(!empty($this->view->scripts)) {
            foreach ($this->view->scripts as $script) {
                echo $script;
            }
        }
    ?>

    <?php
    if(!empty($this->view->styles)) {
        foreach ($this->view->styles as $style) {
            echo $style;
        }
    }
    ?>
</head>
<body>
<div id="wrapper">
    <header>
        <div class="container">
            <div class="title">
                MVC Opdracht
            </div>

            <nav>
                <a href="<?= BASE ?>/content/show">show</a> |
                <a href="<?= BASE ?>/content/add">add</a> |
                <a href="<?= BASE ?>/content/error">try, throw, catch</a> |
                <a href="<?= BASE ?>/gallery/show">gallery</a> |
                <a href="<?= BASE ?>/content/table">show table</a> |
                <a href="<?= BASE ?>/content/invalid">invalid uri</a> |
                <a href="<?= BASE ?>/external/vakanties">external request</a> |
                <a href="<?= BASE ?>/content/internalRequest">internal request</a> |
                <a href="<?= BASE ?>/content/testform">test form</a>
                <?php if(!isset($_SESSION['loggedin']) || $_SESSION['loggedin'] == 'false'): ?>
                    | <a href="<?= BASE ?>/user/login">inloggen</a>
                <?php else: ?>
                    | <a href="<?= BASE ?>/user/logout">uitloggen</a>
                <?php endif; ?>
            </nav>
        </div>

    </header>

    <main class="container">
        <div class="variables">
            <h3>Constants, variables, etc.</h3>
            <b>Constants:</b><br/>
				<pre>
					<?php print_r(get_defined_constants(true)['user']); ?>
				</pre>
            <br/>
            <b>GET values:</b><br/>
				<pre>
					<?php print_r($_GET); ?>
				</pre>
        </div>
        <hr/>
        <?= $this->render; ?>
    </main>

    <footer>
        <div class="container">
            &copy; <?= date('Y'); ?> Michiel Dijk
        </div>
    </footer>
</div>
</body>
</html>