<script src="<?= BASE ?>/js/controllers/content/testform.js"></script>

<form action="<?= BASE ?>/content/testform" method="post">
    <input type="text" name="Klantnr" hidden value="<?= $this->view->testform_Klantnr; ?>">
    <?php if(!empty($this->view->testform_errormessage)) : ?>
        <div class="alert alert-danger">
            <?= $this->view->testform_errormessage; ?>
        </div>
    <?php endif; ?>
    <table>
        <tr>
            <td>
                <label for="Klantnr">Klantnr</label>
            </td>
            <td>
                <input type="text" name="Klantnr_visible" id="Klantnr" disabled value="<?= $this->view->testform_Klantnr; ?>">
            </td>
        </tr>
        <tr>
            <td>
                <label for="Voorletters">Voorletters</label>
            </td>
            <td>
                <input type="text" name="Voorletters" id="Voorletters" value="<?= $this->view->testform_Voorletters; ?>">
            </td>
        </tr>
        <tr>
            <td>
                <label for="Voorvoegsel">Voorvoegsel</label>
            </td>
            <td>
                <input type="text" name="Voorvoegsel" id="Voorvoegsel" value="<?= $this->view->testform_Voorvoegsel; ?>">
            </td>
        </tr>
        <tr>
            <td>
                <label for="Naam">Naam</label>
            </td>
            <td>
                <input type="text" name="Naam" id="Naam" value="<?= $this->view->testform_Naam; ?>">
            </td>
        </tr>
        <tr>
            <td>
                <label for="Adres">Adres</label>
            </td>
            <td>
                <input type="text" name="Adres" id="Adres" value="<?= $this->view->testform_Adres; ?>">
            </td>
        </tr>
        <tr>
            <td>
                <label for="Postcode">Postcode</label>
            </td>
            <td>
                <input type="text" name="Postcode" id="Postcode" oninput="validatePostal(this)" value="<?= $this->view->testform_Postcode; ?>">
            </td>
        </tr>
        <tr>
            <td>
                <label for="Plaats">Plaats</label>
            </td>
            <td>
                <input type="text" name="Plaats" id="Plaats" value="<?= $this->view->testform_Plaats; ?>">
            </td>
        </tr>
        <tr>
            <td>
                <label for="Telefoon">Telefoon</label>
            </td>
            <td>
                <input type="text" name="Telefoon" id="Telefoon" value="<?= $this->view->testform_Telefoon; ?>">
            </td>
        </tr>
        <tr>
            <td>
                <label for="Kredietcode">Kredietcode</label>
            </td>
            <td>
                <input type="text" name="Kredietcode" id="Kredietcode" value="<?= $this->view->testform_Kredietcode; ?>">
            </td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Opslaan">
            </td>
        </tr>
    </table>
</form>

